const Spinner = () => {
    return (
        <svg xmlns="http://www.w3.org/2000/svg" style={{margin: 'auto', backgroundImage: 'none', display: 'block', shapeRendering: 'auto'}} width="150px" height="150px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid">
        <circle cx="50" cy="50" r="35" strokeWidth="8" stroke="#5c5c5c" strokeDasharray="54.97787143782138 54.97787143782138" fill="none" strokeLinecap="round">
        <animateTransform attributeName="transform" type="rotate" dur="1.408450704225352s" repeatCount="indefinite" keyTimes="0;1" values="0 50 50;360 50 50"></animateTransform>
        </circle>
        <circle cx="50" cy="50" r="26" strokeWidth="8" stroke="#232222" strokeDasharray="40.840704496667314 40.840704496667314" strokeDashoffset="40.840704496667314" fill="none" strokeLinecap="round">
        <animateTransform attributeName="transform" type="rotate" dur="1.408450704225352s" repeatCount="indefinite" keyTimes="0;1" values="0 50 50;-360 50 50"></animateTransform>
        </circle>
        {/* [ldio] generated by https://loading.io/ */}
        </svg>
    )   
}

export default Spinner